### ISSUE TITLE
Can I retrieve HAWK_CREDENTIALS from the DB.

### ISSUE THREAD

**Issue by rexposadas** [kumar303/hawkrest#1]
First, thanks for creating this Django package. 

Second, the docs mentioned to include HAWK_CREDENTIALS in  my settings file.  Does the package support retrieving this dict from the database?  My use-case is a long list of mobile devices authenticating to my API.  The information for each device is kept in the DB and would be too many to be manually add in the settings file. A device would serve as a "user" who is allowed to used my API.

Thanks.

**Comment by kumar303** [comment]
Hi. Current hawkrest does not support this. A good patch for this feature would probably be one that follows the Django convention of a callback, like:

```
HAWK_CREDENTIALS = 'import.path.to.callable'
```

where `callable(id)` would return a credentials dict or something like that. There is also a django function to resolve callable paths that you could use.

**Comment by kumar303** [comment]
There is a patch in the works for this: https://github.com/kumar303/hawkrest/pull/5

**Comment by kumar303** [comment]
This feature was added in https://github.com/kumar303/hawkrest/pull/5 and here's the documentation on it: http://hawkrest.readthedocs.org/en/latest/usage.html
