### ISSUE TITLE
How to handle django User authentication, REST Framework throttling, etc?

### ISSUE THREAD

**Issue by kerin** [kumar303/hawkrest#3]
As Hawkrest doesn't make use of django's User model, there seems to be no way to implement API permissions, throttling etc. as they all expect the presence of a User object on request.user. So at the minute it looks like I need to subclass HawkAuthentication to look up and return a User object, which means copy and pasting most of the authenticate() method.

Is there a recommended way of handling population of request.user? Or am I missing something generally?

**Comment by kumar303** [comment]
Hi. A couple replies:
- I just saw this issue, sorry! email filter fail
- A database is not required to use Hawk so there is no user model. I hope that this won't be too much of a problem but I've already run into #9 which was a pretty bad oversight, oops. A fix is forthcoming.
- If you need to return a user object then perhaps you can send a patch for a more abstract version of `HawkAuthentication` for easier subclassing?
