### ISSUE TITLE
Use end-to-end middleware tests

### ISSUE THREAD

**Issue by edmorley** [kumar303/hawkrest#39]
From #38:

> One complication is that properly testing this change to hawkrest means overhauling the tests to actually test the middleware end to end, like eg:
> https://github.com/encode/django-rest-framework/blob/master/tests/test_middleware.py
> 
> (And ideally also overhauling the auth parts too, a la https://github.com/encode/django-rest-framework/blob/master/tests/test_authentication.py)

**Comment by kumar303** [comment]
Seems useful. Thanks for filing.
