### ISSUE TITLE
Verification tool issues

### ISSUE THREAD

**Issue by okayjeff** [kumar303/hawkrest#40]
I have been using hawkrest and found the management command tool handy, although it's broken for later versions of Django and Py3+. Mind if I open a PR to address the issues below? 

1. Django 1.8+ management command API uses `argparse` instead of `optparse`, so using the tool results in an `AttributeError` (BaseCommand has no attribute 'option_list') being raised (at least for 1.11).
2. `ImportError` raised due to attempting to import nonexistent function `lookup_credentials`.
3. `SyntaxError` raised due to `print` not being used as a function as required in py3.
4. Finally, I've added several unit tests for the management command itself.

Some of these have been brought up in other issues, but I have a PR ready to address them if it's ok to contribute.

**Comment by kumar303** [comment]
Fixed in https://github.com/kumar303/hawkrest/pull/41
